--1
SELECT  DISTINCT REPLACEMENT_COST FROM FILM
ORDER BY REPLACEMENT_COST 
--2
SELECT COUNT( DISTINCT (REPLACEMENT_COST) )FROM FILM
--3
SELECT COUNT (TITLE) AS TITLE,COUNT (RATING) AS RATING FROM FILM
WHERE TITLE LIKE 'T%' AND RATING='G' 
--4
SELECT COUNT(COUNTRY) FROM COUNTRY
WHERE COUNTRY LIKE '_____'
--5
SELECT COUNT(CITY) FROM  CITY
WHERE CITY LIKE '%R' OR  CITY LIKE '%r'