
--1
SELECT TITLE, DESCRIPTION
FROM FILM;
--2A
SELECT*FROM FILM
WHERE FILM.LENGTH BETWEEN 60 AND 75;
--2B
SELECT*FROM FILM
WHERE FILM.LENGTH >65 AND FILM.LENGTH<75
--3
SELECT*FROM FILM
WHERE 
    RENTAL_RATE= 0.99 AND
    replacement_cost=12.99 OR replacement_cost= 28.99;
--4
SELECT lAST_NAME FROM CUSTOMER
WHERE FIRST_NAME='Mary'
--5
SELECT * FROM FILM
WHERE   
    FILM.LENGTH<50 AND
    RENTAL_RATE!=2.99 AND RENTAL_RATE!=4.99;
	