--1-
SELECT COUNT(*)
FROM FILM
WHERE LENGTH>
(
    (SELECT AVG(LENGTH)FROM FILM)
   
)

--2-
SELECT COUNT(*) 
FROM FILM
WHERE RENTAL_RATE = 
(
SELECT MAX(RENTAL_RATE) FROM film
)

--3-
SELECT TITLE, RENTAL_RATE, REPLACEMENT_COST 
FROM FILM 
WHERE RENTAL_RATE = 
(SELECT MIN(RENTAL_RATE)FROM FILM) 
AND 
REPLACEMENT_COST = 
(SELECT MIN(replacement_cost)FROM film) 
ORDER BY RENTAL_RATE, REPLACEMENT_COST;

---4-
SELECT * FROM CUSTOMER
WHERE CUSTOMER_ID = ANY 
(
    SELECT CUSTOMER_ID FROM PAYMENT
    GROUP BY CUSTOMER_ID
    ORDER BY COUNT(CUSTOMER_ID) DESC
)
LIMIT 5;
