--1-
SELECT C.CITY, CO.COUNTRY
FROM CITY C
LEFT JOIN COUNTRY CO ON CO.COUNTRY_ID=C.COUNTRY_ID
---2-
SELECT P.PAYMENT_ID,C.FIRST_NAME,C.LAST_NAME
FROM PAYMENT P
RIGHT JOIN CUSTOMER C ON C.CUSTOMER_ID=P.CUSTOMER_ID
---3-
SELECT R.RENTAL_ID,C.FIRST_NAME,C.LAST_NAME
FROM RENTAL R
FULL JOIN CUSTOMER C ON C.CUSTOMER_ID=R.CUSTOMER_ID