--1-
SELECT RATING FROM FILM  
GROUP BY (RATING) 
---2-
SELECT REPLACEMENT_COST, COUNT(*) FILM_SAYISI FROM FILM  
GROUP BY (REPLACEMENT_COST) 
HAVING  (COUNT(*)>50)
--3-
SELECT STORE_ID, COUNT(*) AS MUSTERI_SAYISI FROM CUSTOMER  
GROUP BY (STORE_ID) 
--4-
SELECT COUNTRY_ID, COUNT(COUNTRY_ID ) AS SEHIR_SAYISI FROM CITY
GROUP BY (COUNTRY_ID)
ORDER BY COUNT(COUNTRY_ID) DESC
LIMIT 1;