
--1
SELECT COUNTRY FROM COUNTRY
WHERE
   COUNTRY LIKE'A%a';
---2
SELECT COUNTRY FROM COUNTRY
WHERE COUNTRY LIKE '%_____n' 
   
---3
SELECT TITLE FROM FILM
WHERE
     TITLE LIKE '%t%t%t%t%' or  TITLE LIKE 'T%t%t%t%'
--4
SELECT *FROM FILM F
WHERE
    TITLE LIKE 'C%' AND F.LENGTH>90 AND RENTAL_RATE=2.99