--1
SELECT TITLE,LENGTH FROM FILM
WHERE TITLE LIKE '%n'
ORDER BY LENGTH DESC
LIMIT 5;
--2
SELECT TITLE,LENGTH FROM FILM
WHERE TITLE LIKE '%n'
ORDER BY LENGTH 
OFFSET 5
LIMIT 5;
--3
SELECT LAST_NAME FROM CUSTOMER
WHERE STORE_ID=1
ORDER BY LAST_NAME DESC
LIMIT 4;